/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as baseBaseImport } from './routes/(base)/_base'
import { Route as authAuthImport } from './routes/(auth)/_auth'
import { Route as baseBaseIndexImport } from './routes/(base)/_base.index'
import { Route as baseBaseUsernameIndexImport } from './routes/(base)/_base/$username/index'
import { Route as baseBaseUserUsernameImport } from './routes/(base)/_base/user/$username'

// Create Virtual Routes

const baseImport = createFileRoute('/(base)')()
const authImport = createFileRoute('/(auth)')()
const authAuthRegisterLazyImport = createFileRoute('/(auth)/_auth/register')()
const authAuthLoginLazyImport = createFileRoute('/(auth)/_auth/login')()

// Create/Update Routes

const baseRoute = baseImport.update({
	id: '/(base)',
	getParentRoute: () => rootRoute,
} as any)

const authRoute = authImport.update({
	id: '/(auth)',
	getParentRoute: () => rootRoute,
} as any)

const baseBaseRoute = baseBaseImport.update({
	id: '/_base',
	getParentRoute: () => baseRoute,
} as any)

const authAuthRoute = authAuthImport.update({
	id: '/_auth',
	getParentRoute: () => authRoute,
} as any)

const baseBaseIndexRoute = baseBaseIndexImport.update({
	id: '/',
	path: '/',
	getParentRoute: () => baseBaseRoute,
} as any)

const authAuthRegisterLazyRoute = authAuthRegisterLazyImport
	.update({
		id: '/register',
		path: '/register',
		getParentRoute: () => authAuthRoute,
	} as any)
	.lazy(() => import('./routes/(auth)/_auth.register.lazy').then((d) => d.Route))

const authAuthLoginLazyRoute = authAuthLoginLazyImport
	.update({
		id: '/login',
		path: '/login',
		getParentRoute: () => authAuthRoute,
	} as any)
	.lazy(() => import('./routes/(auth)/_auth.login.lazy').then((d) => d.Route))

const baseBaseUsernameIndexRoute = baseBaseUsernameIndexImport
	.update({
		id: '/$username/',
		path: '/$username/',
		getParentRoute: () => baseBaseRoute,
	} as any)
	.lazy(() => import('./routes/(base)/_base/$username/index.lazy').then((d) => d.Route))

const baseBaseUserUsernameRoute = baseBaseUserUsernameImport.update({
	id: '/user/$username',
	path: '/user/$username',
	getParentRoute: () => baseBaseRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
	interface FileRoutesByPath {
		'/(auth)': {
			id: '/(auth)'
			path: '/'
			fullPath: '/'
			preLoaderRoute: typeof authImport
			parentRoute: typeof rootRoute
		}
		'/(auth)/_auth': {
			id: '/(auth)/_auth'
			path: '/'
			fullPath: '/'
			preLoaderRoute: typeof authAuthImport
			parentRoute: typeof authRoute
		}
		'/(base)': {
			id: '/(base)'
			path: '/'
			fullPath: '/'
			preLoaderRoute: typeof baseImport
			parentRoute: typeof rootRoute
		}
		'/(base)/_base': {
			id: '/(base)/_base'
			path: '/'
			fullPath: '/'
			preLoaderRoute: typeof baseBaseImport
			parentRoute: typeof baseRoute
		}
		'/(auth)/_auth/login': {
			id: '/(auth)/_auth/login'
			path: '/login'
			fullPath: '/login'
			preLoaderRoute: typeof authAuthLoginLazyImport
			parentRoute: typeof authAuthImport
		}
		'/(auth)/_auth/register': {
			id: '/(auth)/_auth/register'
			path: '/register'
			fullPath: '/register'
			preLoaderRoute: typeof authAuthRegisterLazyImport
			parentRoute: typeof authAuthImport
		}
		'/(base)/_base/': {
			id: '/(base)/_base/'
			path: '/'
			fullPath: '/'
			preLoaderRoute: typeof baseBaseIndexImport
			parentRoute: typeof baseBaseImport
		}
		'/(base)/_base/user/$username': {
			id: '/(base)/_base/user/$username'
			path: '/user/$username'
			fullPath: '/user/$username'
			preLoaderRoute: typeof baseBaseUserUsernameImport
			parentRoute: typeof baseBaseImport
		}
		'/(base)/_base/$username/': {
			id: '/(base)/_base/$username/'
			path: '/$username'
			fullPath: '/$username'
			preLoaderRoute: typeof baseBaseUsernameIndexImport
			parentRoute: typeof baseBaseImport
		}
	}
}

// Create and export the route tree

interface authAuthRouteChildren {
	authAuthLoginLazyRoute: typeof authAuthLoginLazyRoute
	authAuthRegisterLazyRoute: typeof authAuthRegisterLazyRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
	authAuthLoginLazyRoute: authAuthLoginLazyRoute,
	authAuthRegisterLazyRoute: authAuthRegisterLazyRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(authAuthRouteChildren)

interface authRouteChildren {
	authAuthRoute: typeof authAuthRouteWithChildren
}

const authRouteChildren: authRouteChildren = {
	authAuthRoute: authAuthRouteWithChildren,
}

const authRouteWithChildren = authRoute._addFileChildren(authRouteChildren)

interface baseBaseRouteChildren {
	baseBaseIndexRoute: typeof baseBaseIndexRoute
	baseBaseUserUsernameRoute: typeof baseBaseUserUsernameRoute
	baseBaseUsernameIndexRoute: typeof baseBaseUsernameIndexRoute
}

const baseBaseRouteChildren: baseBaseRouteChildren = {
	baseBaseIndexRoute: baseBaseIndexRoute,
	baseBaseUserUsernameRoute: baseBaseUserUsernameRoute,
	baseBaseUsernameIndexRoute: baseBaseUsernameIndexRoute,
}

const baseBaseRouteWithChildren = baseBaseRoute._addFileChildren(baseBaseRouteChildren)

interface baseRouteChildren {
	baseBaseRoute: typeof baseBaseRouteWithChildren
}

const baseRouteChildren: baseRouteChildren = {
	baseBaseRoute: baseBaseRouteWithChildren,
}

const baseRouteWithChildren = baseRoute._addFileChildren(baseRouteChildren)

export interface FileRoutesByFullPath {
	'/': typeof baseBaseIndexRoute
	'/login': typeof authAuthLoginLazyRoute
	'/register': typeof authAuthRegisterLazyRoute
	'/user/$username': typeof baseBaseUserUsernameRoute
	'/$username': typeof baseBaseUsernameIndexRoute
}

export interface FileRoutesByTo {
	'/': typeof baseBaseIndexRoute
	'/login': typeof authAuthLoginLazyRoute
	'/register': typeof authAuthRegisterLazyRoute
	'/user/$username': typeof baseBaseUserUsernameRoute
	'/$username': typeof baseBaseUsernameIndexRoute
}

export interface FileRoutesById {
	__root__: typeof rootRoute
	'/(auth)': typeof authRouteWithChildren
	'/(auth)/_auth': typeof authAuthRouteWithChildren
	'/(base)': typeof baseRouteWithChildren
	'/(base)/_base': typeof baseBaseRouteWithChildren
	'/(auth)/_auth/login': typeof authAuthLoginLazyRoute
	'/(auth)/_auth/register': typeof authAuthRegisterLazyRoute
	'/(base)/_base/': typeof baseBaseIndexRoute
	'/(base)/_base/user/$username': typeof baseBaseUserUsernameRoute
	'/(base)/_base/$username/': typeof baseBaseUsernameIndexRoute
}

export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath
	fullPaths: '/' | '/login' | '/register' | '/user/$username' | '/$username'
	fileRoutesByTo: FileRoutesByTo
	to: '/' | '/login' | '/register' | '/user/$username' | '/$username'
	id:
		| '__root__'
		| '/(auth)'
		| '/(auth)/_auth'
		| '/(base)'
		| '/(base)/_base'
		| '/(auth)/_auth/login'
		| '/(auth)/_auth/register'
		| '/(base)/_base/'
		| '/(base)/_base/user/$username'
		| '/(base)/_base/$username/'
	fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
	authRoute: typeof authRouteWithChildren
	baseRoute: typeof baseRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
	authRoute: authRouteWithChildren,
	baseRoute: baseRouteWithChildren,
}

export const routeTree = rootRoute
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(auth)",
        "/(base)"
      ]
    },
    "/(auth)": {
      "filePath": "(auth)",
      "children": [
        "/(auth)/_auth"
      ]
    },
    "/(auth)/_auth": {
      "filePath": "(auth)/_auth.tsx",
      "parent": "/(auth)",
      "children": [
        "/(auth)/_auth/login",
        "/(auth)/_auth/register"
      ]
    },
    "/(base)": {
      "filePath": "(base)",
      "children": [
        "/(base)/_base"
      ]
    },
    "/(base)/_base": {
      "filePath": "(base)/_base.tsx",
      "parent": "/(base)",
      "children": [
        "/(base)/_base/",
        "/(base)/_base/user/$username",
        "/(base)/_base/$username/"
      ]
    },
    "/(auth)/_auth/login": {
      "filePath": "(auth)/_auth.login.lazy.tsx",
      "parent": "/(auth)/_auth"
    },
    "/(auth)/_auth/register": {
      "filePath": "(auth)/_auth.register.lazy.tsx",
      "parent": "/(auth)/_auth"
    },
    "/(base)/_base/": {
      "filePath": "(base)/_base.index.tsx",
      "parent": "/(base)/_base"
    },
    "/(base)/_base/user/$username": {
      "filePath": "(base)/_base/user/$username.tsx",
      "parent": "/(base)/_base"
    },
    "/(base)/_base/$username/": {
      "filePath": "(base)/_base/$username/index.tsx",
      "parent": "/(base)/_base"
    }
  }
}
ROUTE_MANIFEST_END */
