export const MUTATION_KEYS = {
	POST_AUTH_REGISTER: 'POST_AUTH_REGISTER',
	POST_AUTH_LOGIN: 'POST_AUTH_LOGIN',
	POST_POSTS: 'POST_POSTS',
	PATCH_POSTS: 'PATCH_POSTS',
	DELETE_POSTS: 'DELETE_POSTS',
}

export const QUERY_KEYS = {
	GET_USER: 'GET_USER',
	GET_PROFILE: 'GET_PROFILE',
	GET_POSTS: 'GET_POSTS',
}
