export const MUTATION_KEYS = {
	POST_REGISTER: 'POST_REGISTER',
	POST_LOGIN: 'POST_LOGIN',
}

export const QUERY_KEYS = {
	GET_USER: 'GET_USER',
	GET_USER_POSTS: 'GET_USER_POSTS',
	GET_PROFILE: 'GET_PROFILE',
}
